# Generated by Django 5.0.6 on 2024-06-02 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_initial'),
        ('project', '0010_gig_freelancers_gig_number_of_freelancers'),
        ('user', '0005_alter_freelancer_certification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('paid_amount', models.IntegerField(blank=True, null=True)),
                ('received_amount', models.IntegerField(blank=True, null=True)),
                ('transaction_fee', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100)),
                ('due_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('tax', models.IntegerField(blank=True, null=True)),
                ('paid_currency', models.CharField(blank=True, max_length=100)),
                ('received_currency', models.CharField(blank=True, max_length=100)),
                ('transaction_fee_currency', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_companies', to='user.company')),
                ('document', models.ManyToManyField(blank=True, related_name='invoice_document', to='common.document')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer', to='user.freelancer')),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_gigs', to='project.gig')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_projects', to='project.project')),
            ],
        ),
    ]
