# Generated by Django 5.0.6 on 2024-06-02 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('project', '0011_alter_gig_project_alter_gig_user'),
        ('user', '0005_alter_freelancer_certification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_companies', to='user.company'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='freelancer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='freelancer', to='user.freelancer'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='gig',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_gigs', to='project.gig'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_projects', to='project.project'),
        ),
    ]
